name: Test action
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
      repo:
        required: false
        type: string
      branch:
        required: false
        type: string

jobs:
  test:
    name: Test on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      with:
        version: ${{ inputs.version || 'latest' }}
        repo: ${{ inputs.repo || 'koush/scrypted' }}
        branch: ${{ inputs.branch || 'main' }}
